branch-defaults:
  elastic-beanstalk-integration:
    environment: nommox
    group_suffix: null
  nommox/pedro-guerra/users-cases:
    environment: nommox
global:
  application_name: nommox
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.5 (Passenger Standalone)
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
