branch-defaults:
  master:
    environment: NommoxApp
environment-defaults:
  NommoxApp:
    branch: null
    repository: null
global:
  application_name: nommox-app
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Puma with Ruby 2.6
    running on 64bit Amazon Linux/2.10.2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
