[
  {
    "id": "010000",
    "name": "Amazonas",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "020000",
    "name": "Áncash",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "030000",
    "name": "Apurímac",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "040000",
    "name": "Arequipa",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "050000",
    "name": "Ayacucho",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "060000",
    "name": "Cajamarca",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "070000",
    "name": "Callao",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "080000",
    "name": "Cusco",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "090000",
    "name": "Huancavelica",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "100000",
    "name": "Huánuco",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "110000",
    "name": "Ica",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "120000",
    "name": "Junín",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "130000",
    "name": "La Libertad",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "140000",
    "name": "Lambayeque",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "150000",
    "name": "Lima",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "160000",
    "name": "Loreto",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "170000",
    "name": "Madre de Dios",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "180000",
    "name": "Moquegua",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "190000",
    "name": "Pasco",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "200000",
    "name": "Piura",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "210000",
    "name": "Puno",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "220000",
    "name": "San Martín",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "230000",
    "name": "Tacna",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "240000",
    "name": "Tumbes",
    "created_at": null,
    "updated_at": null
  },
  {
    "id": "250000",
    "name": "Ucayali",
    "created_at": null,
    "updated_at": null
  }
]
